name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #
  # Linters checker
  #
  linters:
    name: Linters
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    strategy:
      matrix:
        go-version: [1.15.8]

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/alibaba/accelerated-container-image

      - name: set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: golangci-lint check
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36.0
          working-directory: src/github.com/alibaba/accelerated-container-image
          args: --timeout=5m
